shell = "zsh"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-async]
github = "mafredri/zsh-async"
