global:
  scrape_interval: 15s
  scrape_timeout: 15s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: docker
    static_configs:
      - targets: ["cadvisor:8080"]
