{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Plex Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"plex\"}[1m])",
     "legendFormat": "Transmitted"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"plex\"}[1m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Resilio Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"resilio-sync\"}[1m])",
     "legendFormat": "Transmitted"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"resilio-sync\"}[1m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Plex Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"plex\"}[1m])",
     "legendFormat": "CPU"
    },
    {
     "expr": "container_memory_usage_bytes{name=\"plex\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Resilio Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"resilio-sync\"}[1m])",
     "legendFormat": "CPU"
    },
    {
     "expr": "container_memory_usage_bytes{name=\"resilio-sync\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pi-Hole",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_blocked_today", "legendFormat": "Ads Total" },
    { "expr": "pihole_ads_percentage_today", "legendFormat": "Ads Percentage" },
    { "expr": "pihole_domains_being_blocked", "legendFormat": "Domains" }
   ]
  }
 ]
}