services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.containers/Caddyfile:/etc/caddy/Caddyfile
      - ~/.config/caddy_data:/data
      - ~/.config/caddy_config:/config
    networks:
      - caddy_net
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
    external: true
