version: "3.8"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.containers/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - caddy_net
    restart: unless-stopped

networks:
  caddy_net:
    external: true
