FROM golang:alpine3.18 AS build

RUN apk add build-base git

WORKDIR /app
RUN git clone https://github.com/nkanaev/yarr.git
WORKDIR /app/yarr
RUN make build_linux
WORKDIR /app/yarr/src

FROM alpine:latest

RUN apk add --no-cache ca-certificates && \
    update-ca-certificates

COPY --from=build /app/yarr/_output/linux/yarr /usr/local/bin/yarr

EXPOSE 7070
