---
version: '3.7'

services:
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - "8080:80"
    volumes:
      - /media:/srv
      - ~/.config/filebrowser/filebrowser.db:/database/filebrowser.db
      - ~/.config/filebrowser/settings.json:/config/settings.json
    environment:
      - PUID=1000
      - PGID=1000
    user: "0"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"