version: "3"
services:
  focalboard:
    image: mattermost/focalboard:latest
    container_name: focalboard
    ports:
      - 127.0.0.1:8282:8000
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
