version: "3.9"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    user: 1000:1000
    devices:
      - /dev/ttyUSB0
    depends_on:
      - mosquitto
      - zigbee2mqtt
      - nodered
    volumes:
      - /opt/smart-home/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    privileged: true
    network_mode: host

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    user: 1000:1000
    depends_on:
      - homeassistant
      - mosquitto
      - zigbee2mqtt
    environment:
      - TZ=America/New_York
    ports:
      - "1880:1880"
    volumes:
      - /opt/smart-home/nodered:/data
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /opt/smart-home/mosquitto/config:/mosquitto/config
      - /opt/smart-home/mosquitto/data:/mosquitto/data
      - /opt/smart-home/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - TZ=America/New_York
    restart: always

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - /opt/smart-home/z2m:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8099:8080
    environment:
      - TZ=America/New_York
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0

  hass-configurator:
    image: "causticlab/hass-configurator-docker:latest"
    restart: always
    ports:
      - "3218:3218/tcp"
    volumes:
      - "/opt/smart-home/hass/configurator-config:/config"
      - "/opt/smart-home/hass/hass-config:/hass-config"
