---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    restart: unless-stopped
    volumes:
      - ~/.config/jellyfin:/config
      - /media/Movies:/data/movies
      - /media/Rentals:/data/rentals
      - /media/TV_Shows:/data/tvshows
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
