---
version: "3.3"
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: ~/.config/komga
        target: /config
      - type: bind
        source: ~/.config/komga/data
        target: /data
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /media/Books
        target: /Books
        read_only: true
      - type: bind
        source: /media/Comics
        target: /Comics
        read_only: true
      - type: bind
        source: /media/Manga
        target: /Manga
        read_only: true
    ports:
      - 25600:25600
    user: "1000:1000"
    environment:
      KOMGA_LIBRARIES_SCAN_STARTUP: "true"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"