version: "3.8"
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus-data: {}
  grafana-data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 127.0.0.1:9000:9090
    networks:
      - "monitoring"
    restart: unless-stopped
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - "monitoring"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - "monitoring"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    ports:
      - 127.0.0.1:9617:9617
    networks:
      - "monitoring"
    environment:
        - PIHOLE_HOSTNAME=192.168.1.151
        - PIHOLE_PASSWORD=
        - INTERVAL=15s
        - PORT=9617
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  grafana:
    image: grafana/grafana:latest
    ports:
      - 127.0.0.1:4000:3000
    networks:
      - "monitoring"
    restart: unless-stopped
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
