version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    user: plex
    restart: unless-stopped
    volumes:
      - /Library/Application Support/Plex Media Server:/config
      - /mnt/Anime/:/Anime
      - /mnt/Audiobooks:/Audiobooks
      - /mnt/Movies:/Movies
      - /mnt/Music:/Music
      - ~/Rentals:/Rentals
      - /mnt/TV_Shows:/TV_Shows
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    user: plex
    restart: unless-stopped
    volumes:
      - ~/.config/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - 127.0.0.1:8181:8181
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
