services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    restart: unless-stopped
    volumes:
      - /Library/Application Support/Plex Media Server:/config
      - /Volumes/Samuel/Audiobooks:/Audiobooks
      - /Volumes/Samuel/Music:/Music
    ports:
      - "32400:32400"
    environment:
      - PUID=501
      - PGID=20
      - VERSION=docker
      - TZ=America/New_York
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ~/.config/tautulli:/config
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    ports:
      - 127.0.0.1:8181:8181
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
