---
services:
  sftpgo:
    image: drakkan/sftpgo:latest
    container_name: sftpgo
    ports:
      - "2020:22"
      - "8080:8080" # Optional: Web management interface
    volumes:
      - ./sftpgo_data:/data
      - /media/Emulation:/Emulation
    environment:
      - SFTPGO_ADMIN_USER=admin
      - SFTPGO_ADMIN_PASSWORD=your_password
      - SFTPGO_LOG_LEVEL=info # Adjust logging level as needed
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
 