version: '3.8'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/Books:/Books
      - /mnt/Comics:/Comics
      - /mnt/Manga:/Manga
    command: '-s "Books;/mnt/Books;yes;no;no;fourjuaneight" -s "Comics;/mnt/Comics;yes;no;no;fourjuaneight" -s "Manga;/mnt/Manga;yes;no;no;fourjuaneight" -u "fourjuaneight;admin" -p'

networks:
  default:
