version: '3.8'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/mnt
    env_file: .env
    command: '-s "Media;/mnt;yes;no;no;fourjuaneight" -u "fourjuaneight;${SMB_PASSWORD}" -p'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
