version: "3.3"
services:
  stump:
    image: aaronleopold/stump
    container_name: stump
    volumes:
      - ~/.config/stump:/config
      - ~/.config/stump/data:/data
      - ~/Books:/books
      - ~/Comics:/comics
      - ~/Manga:/manga
    ports:
      - 10801:10801
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - STUMP_LOG_VERBOSITY=4
      - RUST_BACKTRACE=1
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
