---
services:
  stump:
    image: aaronleopold/stump:nightly
    container_name: stump
    volumes:
      - ~/.config/stump:/config
      - ~/.config/stump/data:/data
      - /media/Books:/Books
      - /media/Comics:/Comics
      - /media/Manga:/Manga
    ports:
      - 10801:10801
    environment:
      - PUID=1000
      - PGID=1000
      - STUMP_LOG_VERBOSITY=4
      - RUST_BACKTRACE=1
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
