python3 -m pip install autopep8
python3 -m pip install b2
python3 -m pip install brotli
python3 -m pip install flake8
python3 -m pip install fonttools
python3 -m pip install ipython
python3 -m pip install proselint
python3 -m pip install requests
python3 -m pip install vim-vint
python3 -m pip install virtualenv
python3 -m pip install virtualenvwrapper