#!/usr/bin/env bash

###
# Steam Controller wake-from-sleep for Bazzite living-room rig.
#
# Hardware assumptions (fixed):
#   Steam Controller (2026) → Puck (2.4GHz USB-C dongle, Valve 28de:1304) → rig
#
# Out of the box the Puck cannot wake Fedora or Bazzite. USB remote wakeup is
# disabled by default on every port; SteamOS only works because Valve ships it
# pre-enabled. This script enables it via a persistent udev rule.
#
# Bluetooth mode CANNOT wake the machine. Puck only. This is a protocol limit,
# not a config problem — no rule will fix a Bluetooth connection.
#
# Rule lands in /etc/udev/rules.d/, which ostree 3-way merges on rebase. No
# layering, no /usr writes, survives updates.
#
# Bus numbers are physical. The rule pins the root hub the Puck is currently
# on, so moving the Puck to a different port breaks wake. Safe to re-run — it
# re-detects and rewrites the rule.
#
# Pairs with cec.sh: this wakes the PC, that wakes the TV.
###

source ~/dotfiles/util/echos.sh

set -euo pipefail

VENDOR="28de"
PRODUCT="1304"
RULE_FILE="/etc/udev/rules.d/99-controller-wake.rules"

minibot "Setting up Steam Controller wake-from-sleep."

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------

action "locating Steam Controller Puck"
DEV_PATH=""
for d in /sys/bus/usb/devices/*/; do
  [[ -r "$d/idVendor" && -r "$d/idProduct" ]] || continue
  if [[ "$(cat "$d/idVendor")" == "$VENDOR" && "$(cat "$d/idProduct")" == "$PRODUCT" ]]; then
    DEV_PATH="${d%/}"
    break
  fi
done

if [[ -z "$DEV_PATH" ]]; then
  error "Puck not found ($VENDOR:$PRODUCT)."
  warn "Check, in order:"
  warn "  1. Puck is plugged in (USB-C dongle, not the controller cable)"
  warn "  2. Controller is in Puck mode, not Bluetooth"
  warn "  3. lsusb | grep -i valve  — confirm it enumerates at all"
  warn "  4. If the ID differs, Valve shipped a revision. Update VENDOR/PRODUCT above."
  exit 1
fi

DEV_NODE="$(basename "$DEV_PATH")"
BUS_NUM="$(cat "$DEV_PATH/busnum")"
ROOT_HUB="usb${BUS_NUM}"
ok "Puck at $DEV_NODE on bus $BUS_NUM (root hub $ROOT_HUB)."

action "checking ACPI wakeup for xHCI controllers"
if grep -qiE '^XHC.*\*enabled' /proc/acpi/wakeup; then
  ok "xHCI armed at ACPI level."
else
  error "no xHCI controller is ACPI-wake-enabled."
  warn "ACPI is blocking wake above the udev layer. Fix in BIOS first:"
  warn "  - 'Wake from USB' / 'USB Wake Support' / 'Resume By USB Device' = Enabled"
  warn "  - 'ErP Ready' (ASUS/MSI/Gigabyte) or 'Deep Sleep' (ASRock)  = Disabled"
  warn ""
  warn "Current state:"
  grep -i xhc /proc/acpi/wakeup | sed 's/^/  /' || warn "  (no XHC entries at all)"
  exit 1
fi

action "checking sleep state"
MEM_SLEEP="$(cat /sys/power/mem_sleep)"
if [[ "$MEM_SLEEP" == *"[deep]"* ]]; then
  ok "sleep state is deep (S3)."
elif [[ "$MEM_SLEEP" == *"[s2idle]"* ]]; then
  ok "sleep state is s2idle."
else
  warn "unexpected sleep state: $MEM_SLEEP"
fi

# ---------------------------------------------------------------------------
# Install rule
# ---------------------------------------------------------------------------

action "writing udev rule to $RULE_FILE"
sudo tee "$RULE_FILE" >/dev/null <<RULE
# Steam Controller wake-from-sleep. Generated by lib/bazzite/controller-wake.sh
# Root hub carrying the Puck. Bus number is physical — re-run this script if
# the Puck is moved to a different port.
ACTION=="add", SUBSYSTEM=="usb", KERNEL=="${ROOT_HUB}", TEST=="power/wakeup", ATTR{power/wakeup}="enabled"
# Steam Controller Puck itself.
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="${VENDOR}", ATTRS{idProduct}=="${PRODUCT}", TEST=="power/wakeup", ATTR{power/wakeup}="enabled"
RULE

sudo chmod 644 "$RULE_FILE"
sudo restorecon "$RULE_FILE" 2>/dev/null || true

action "reloading udev"
sudo udevadm control --reload

# udevadm trigger defaults to action 'change'. These rules key on 'add' and
# will silently never fire without this.
action "triggering add events on usb subsystem"
sudo udevadm trigger --action=add --subsystem-match=usb
sudo udevadm settle

# ---------------------------------------------------------------------------
# Verify
# ---------------------------------------------------------------------------

action "verifying wakeup flags"
FAILED=0

HUB_STATE="$(cat "/sys/bus/usb/devices/${ROOT_HUB}/power/wakeup" 2>/dev/null || echo missing)"
if [[ "$HUB_STATE" == "enabled" ]]; then
  ok "root hub $ROOT_HUB enabled."
else
  error "root hub $ROOT_HUB is '$HUB_STATE', expected 'enabled'."
  FAILED=1
fi

DEV_STATE="$(cat "$DEV_PATH/power/wakeup" 2>/dev/null || echo missing)"
if [[ "$DEV_STATE" == "enabled" ]]; then
  ok "Puck $DEV_NODE enabled."
else
  error "Puck $DEV_NODE is '$DEV_STATE', expected 'enabled'."
  FAILED=1
fi

if [[ -f "$RULE_FILE" ]]; then
  ok "rule installed at $RULE_FILE."
else
  error "rule missing at $RULE_FILE."
  FAILED=1
fi

if [[ $FAILED -ne 0 ]]; then
  error "setup incomplete. See errors above."
  warn "Debug the rule match with:"
  warn "  udevadm test $DEV_PATH 2>&1 | grep -i wakeup"
  exit 1
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

ok "done configuring controller wake."

minibot "Test and caveats:"
warn "  1. systemctl suspend, wait for fans to stop, press the Steam button."
warn "  2. Reboot and re-run this script — it re-verifies. Both flags should"
warn "     still read 'enabled' without any manual trigger."
warn ""
warn "If it does not wake:"
warn "  - Confirm BIOS USB wake is on and ErP / Deep Sleep is off."
warn "  - Try s2idle live:  echo s2idle | sudo tee /sys/power/mem_sleep"
warn "    If that works, persist it:"
warn "      rpm-ostree kargs --append=mem_sleep_default=s2idle"
warn "    Costs more idle power than deep. Only if deep will not cooperate."
warn "  - Read the wake source:"
warn "      journalctl -b -1 --no-pager | grep -iE 'wakeup|resume|PM:' | tail -20"
warn ""
warn "Known behavior, not faults:"
warn "  - Puck must be plugged in BEFORE suspend. Inserted while asleep = no wake."
warn "  - Bluetooth mode cannot wake. Puck only."
warn "  - Powering the controller off can bounce the box awake. Let idle-suspend"
warn "    handle sleep and use the Steam button only to wake."
warn "  - Moving the Puck to another port breaks the root hub rule. Re-run this."
warn ""
warn "TV wake is separate — that is HDMI-CEC. See cec.sh."
