name: Setup macOS environment

on:
  push

jobs:
  macos-install:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          

      - name: Install dependencies
        run: |
          ./install.sh
